apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-mongo-ns
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: AdminPass123
  APP_DB_USER: appuser
  APP_DB_PASS: AppPass123
